Write a Python program to sum all the items in a list.

In [3]:
import functools
l1=[2,3,5,4,6,1,2]
print(functools.reduce(lambda x,y:x+y,l1))

23


In [10]:
count=0
for i in l1:
    count+=i
print(count)

23


Write a Python program to multiplies all the items in a list.

In [11]:
l1=[2,3,5,4,6,1,2]
count1=1
for i in l1:
    count1*=i
print(count1)

1440


In [12]:
def multiply(items):
    count=1
    for i in items:
        count*=i
    return count
print(multiply([2,5,6,3,4,6,9,45]))

1749600


 Write a Python program to get the largest number from a list.

In [16]:
print(functools.reduce(lambda a,b:a if a>b else b,l1))

6


In [19]:
def largest(items):
    max=0
    for i in items:
        if i>max:
            max=i
    return max
print(largest([2,3,4,-5,1,44]))

44


Write a Python program to get the smallest number from a list.

In [21]:
def smallest(items):
    min=0
    for i in items:
        if i<min:
            min=i
    return min
print(smallest([-8,-2,-1,5,3,4,7,9]))

-8


Write a Python program to count the number of strings where the string length is 2 or more and the first and last character are same from a given list of strings.

In [25]:
def count1(items):
    count=0
    for i in items:
        if len(i)>1 and i[0]==i[-1]:
            count+=1
    return count
print(count1(['abc', 'xyz', 'aba', '1221']))

2


Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a given list of non-empty tuples

In [42]:
def last(n):
    return n[-1]

def sort1(items):
    return sorted(items,key=last)
    
print(sort1([(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]))

[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


sort in ascending order

In [38]:

def sort1(items):
    return sorted(items)
    
print(sort1([(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]))

[(1, 2), (2, 1), (2, 3), (2, 5), (4, 4)]


Write a Python program to remove duplicates from a list.

In [46]:
l1=[2,5,6,3,2,4,5,9,7,9]
dup=set()
unique=[]
for i in l1:
    if i not in dup:
        unique.append(i)
        dup.add(i)
print(unique)

        

[2, 5, 6, 3, 4, 9, 7]


Write a Python program to check a list is empty or not.

In [48]:
l1=[]
if not l1:
    print('emply list')
    

emply list


 Write a Python program to clone or copy a list.

In [50]:
l1=[32,65,45,9,15,3]
l2=l1.copy()
l2

[32, 65, 45, 9, 15, 3]

In [53]:
l3=l1
l3

[32, 65, 45, 9, 15, 3]

 Write a Python program to find the list of words that are longer than n from a given list of words

In [66]:
str1='The quick brown fox jumps over the lazy dog'
n=3
txt = str1.split(" ")
a=[i for i in txt if len(i)>n]
print(a)

['quick', 'brown', 'jumps', 'over', 'lazy']


In [67]:
def long_words(n, str):
    word_len = []
    txt = str.split(" ")
    for x in txt:
        if len(x) > n:
            word_len.append(x)
    return word_len	
print(long_words(3, "The quick brown fox jumps over the lazy dog"))

['quick', 'brown', 'jumps', 'over', 'lazy']


Write a Python function that takes two lists and returns True if they have at least one common member.

In [73]:
def compare(l1,l2):
    result=False
    for i in l1:
        for j in l2:
            if l1==l2:
                result=True
    return result
print(compare([2,3,4,5,6,7,8,9],[5,12,6,4,9,2]))

False


In [80]:
def setcompare(l1,l2):
    a=set(l1)
    b=set(l2)
    if (a&b):
        return (a&b)
    else:
        return False
print(setcompare([2,3,4,5,6,7,8,9],[2,3,4,9,7,6,2,5]))
print(setcompare([2,3,4,5,6,7,8,9],[15,16,17,19,20]))

{2, 3, 4, 5, 6, 7, 9}
False


Write a Python program to print a specified list after removing the 0th, 4th and 5th elements.

In [94]:
def removelist(l1):
    l1.pop(0)
    l1.pop(4)
    l1.pop(5)
    return l1
print(removelist([6,2,4,8,9,3,4,6,7]))
print(removelist(['red','green','blue','yellow','black','white','orange','brown']))

[2, 4, 8, 9, 4, 7]
['green', 'blue', 'yellow', 'black', 'orange']


In [89]:
color=['red','green','blue','yellow','black','white','orange']
a=[x for (i,x) in enumerate(color) if i not in (0,4,5)]
print(a)

['green', 'blue', 'yellow', 'orange']


Write a Python program to generate a 3*4*6 3D array whose each element is *.

In [102]:
a=[[['*' for i in range(6)] for i in range(4)] for i in range(3)]
print(a)

[[['*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*']], [['*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*']], [['*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*'], ['*', '*', '*', '*', '*', '*']]]


Write a Python program to print the numbers of a specified list after removing even numbers from it

In [103]:
def removeeven(l1):
    a=[]
    for i in l1:
        if i%2!=0:
            a.append(i)
    return a
print(removeeven(range(0,50)))
            

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [107]:
a=[i for i in range(0,50) if i%2!=0]
print(a)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


Write a Python program to shuffle and print a specified list

In [111]:
from random import shuffle
color=['red','green','blue','yellow','black','white','orange']
shuffle(color)
color

['blue', 'black', 'white', 'red', 'yellow', 'orange', 'green']

Write a Python program to generate and print a list of first and last 5 elements where the values are square of numbers between 1 and 30 (both included).

In [114]:
l=[]
for i in range(1,30):
    l.append(i**2)
print(l[:5]+l[-5:])
    

[1, 4, 9, 16, 25, 625, 676, 729, 784, 841]


In [115]:
a=[i**2 for i in range(1,30)]
print(a[:5]+a[-5:])

[1, 4, 9, 16, 25, 625, 676, 729, 784, 841]


Write a Python program to generate and print a list except for the first 5 elements, where the values are square of numbers between 1 and 30 (both included)

In [116]:
a=[i**2 for i in range(1,30)]
print(a[6:])

[49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841]


 Write a Python program to generate all permutations of a list in Python

Write a Python program to generate all permutations of a list in Python.

In mathematics, the notion of permutation relates to the act of arranging all the members of a set into some sequence or order, or if the set is already ordered, rearranging (reordering) its elements, a process called permuting. These differ from combinations, which are selections of some members of a set where order is disregarded.

In the following image each of the six rows is a different permutation of three distinct balls.

In [118]:
import itertools
print(list(itertools.permutations([3,5,2])))

[(3, 5, 2), (3, 2, 5), (5, 3, 2), (5, 2, 3), (2, 3, 5), (2, 5, 3)]


Write a Python program to get the difference between the two lists.

In [125]:
l1=[1,2,3,4]
l2=[1,2]
print(set(l1)-set(l2))

{3, 4}


Write a Python program access the index of a list.

In [126]:
num=[2,6,4,7,9]
for idx,i in enumerate(num):
    print(idx,i)

0 2
1 6
2 4
3 7
4 9


In [130]:
a=[(i,x) for (i,x) in enumerate(num)]
print(a)

[(0, 2), (1, 6), (2, 4), (3, 7), (4, 9)]


Write a Python program to convert a list of characters into a string.

In [131]:
l=['p','y','t','h','o','n']
print(''.join(l))

python


Write a Python program to find the index of an item in a specified list.

In [132]:
l=['p','y','t','h','o','n']
l.index('h')

3

Write a Python program to flatten a shallow list.

In [143]:
import itertools
original_list = [[2,4,3],[1,5,6], [9], [7,9,0]]
a=list(itertools.chain(*original_list))
print(a)

[2, 4, 3, 1, 5, 6, 9, 7, 9, 0]


Write a Python program to append a list to the second list.

In [148]:
l1=[1,2,3,4]
l2=[1,2]
l1.extend(l2)
print(l1)

[1, 2, 3, 4, 1, 2]


In [149]:
l1=[1,2,3,4]
l2=[1,2]
l3=l1+l2
print(l3)

[1, 2, 3, 4, 1, 2]


Write a Python program to select an item randomly from a list.

In [153]:
import random
color=['red','green','blue','yellow','black','white','orange']
print(random.choice(color))

yellow


Write a python program to check whether two lists are circularly identical.

In [154]:
list1 = [10, 10, 0, 0, 10]
list2 = [10, 10, 10, 0, 0]
list3 = [1, 10, 10, 0, 0]

print('Compare list1 and list2')
print(' '.join(map(str, list2)) in ' '.join(map(str, list1 * 2)))
print('Compare list1 and list3')
print(' '.join(map(str, list3)) in ' '.join(map(str, list1 * 2)))

Compare list1 and list2
True
Compare list1 and list3
False


Write a Python program to find the second smallest number in a list.

In [163]:
numbers = [1, 3, 4, 2] 
numbers.sort() 
print(numbers) 

[1, 2, 3, 4]


In [173]:
num=[5,6,4,7,9,2,8,1]
num.sort()
print(num)
print(num[1])

[1, 2, 4, 5, 6, 7, 8, 9]
2


In [175]:
def second_smallest(numbers):
    if (len(numbers)<2):
        return
    if ((len(numbers)==2)  and (numbers[0] == numbers[1]) ):
        return
    dup_items = set()
    uniq_items = []
    for x in numbers:
        if x not in dup_items:
            uniq_items.append(x)
            dup_items.add(x)
            uniq_items.sort()    
    return  uniq_items[1]   

print(second_smallest([1, 2, -8, -2, 0, -2]))
print(second_smallest([1, 1, 0, 0, 2, -2, -2]))
print(second_smallest([1, 1, 1, 0, 0, 0, 2, -2, -2]))
print(second_smallest([2,2]))
print(second_smallest([2]))

-2
0
0
None
None


Write a Python program to find the second largest number in a list.

In [176]:
def second_smallest(numbers):
    if (len(numbers)<2):
        return
    if ((len(numbers)==2)  and (numbers[0] == numbers[1]) ):
        return
    dup_items = set()
    uniq_items = []
    for x in numbers:
        if x not in dup_items:
            uniq_items.append(x)
            dup_items.add(x)
            uniq_items.sort()    
    return  uniq_items[-2]   

print(second_smallest([1, 2, -8, -2, 0, -2]))
print(second_smallest([1, 1, 0, 0, 2, -2, -2]))
print(second_smallest([1, 1, 1, 0, 0, 0, 2, -2, -2]))
print(second_smallest([2,2]))
print(second_smallest([2]))

1
1
1
None
None


Write a Python program to get unique values from a list.

In [191]:
l1=[1,5,7,9,2,6,4,8,2,5,7]
dup=set()
unique=[]
for i in l1:
    if i not in dup:
        unique.append(i)
        dup.add(i)
print(unique)

[1, 5, 7, 9, 2, 6, 4, 8]


In [185]:
l1=[1,5,7,9,2,6,4,8,2,5,7]
unique=set(l1)
print(unique)

{1, 2, 4, 5, 6, 7, 8, 9}


Write a Python program to get the frequency of the elements in a list.

In [192]:
import collections
l1=[1,5,7,9,2,6,4,8,2,5,7]
print(collections.Counter(l1))

Counter({5: 2, 7: 2, 2: 2, 1: 1, 9: 1, 6: 1, 4: 1, 8: 1})


In [196]:
l1=[1,5,7,9,2,6,4,8,2,5,7]
dict={}
for i in l1:
    key=dict.keys()
    if i in key:
        dict[i]+=1
    else:
        dict[i]=1
print(dict)


{1: 1, 5: 2, 7: 2, 9: 1, 2: 2, 6: 1, 4: 1, 8: 1}


In [198]:
a = {}
a[1] = 1
a['1'] = 2
a[1]=a[1]+1
count = 0
for i in a:
    count += a[i]
print(count)
print(a)


4
{1: 2, '1': 2}


In [202]:
import numpy as np
row=int(input('enter value for x'))
col=int(input('enter value for y'))
D=[[0 for col in range(col)] for row in range(row)]
for row1 in range(row):
    for col1 in range(col):
        D[row1][col1]=row1*col1
print(np.matrix(D))

enter value for x3
enter value for y5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [203]:
import numpy as np

In [210]:
dt = np.dtype([('Item', np.unicode_, 16), ('Count', np.int32),('Amount',np.float64)]) 
x = np.array([('vegetable',3, 454.2), ('almond',15, 762.1),('cake',5,200),('cashew',20,1400.4)], dtype=dt) 
print(x)

[('vegetable',  3,  454.2) ('almond', 15,  762.1) ('cake',  5,  200. )
 ('cashew', 20, 1400.4)]


In [211]:
print(x['Count'])

[ 3 15  5 20]


In [212]:
print(x[:2]['Count'])

[ 3 15]


In [1]:
l=[4, 7, 9, 6, 3, 2]

In [3]:
def swap(l, item1, item2): 
    l[item1],l[item2] = l[item2],l[item1] 
    return l
print(swap(l, 0, 5))

[2, 7, 9, 6, 3, 4]
