Datastructures;1,2,3 level drill down in dict,Array slicing,Arithmetic operations,Dot product,Comparison operator,Logical operator,Array collapsing

In [68]:
#array-scalar type
dt=np.dtype(np.int32)
print(dt)

int32


In [69]:
#int8,int16,int32,int64 can b replaced with equivalent string 'i1','i2','i4','i8'...
#float 'f4','f8'...
#string 'S10','S20','S64'...
dt=np.dtype('i4')
dt

dtype('int32')

In [71]:
i16=np.dtype(np.int16)#np.dtype('i2')
print(i16)

int16


In [73]:
#create a list
lst=[[3.4,8.7,9.9],[1.1,-7.8,-0.7],[4.1,12.3,4.8]]
print(type(lst))
i8=np.dtype(np.int8)
a=np.array(lst,dtype=i8)
print(a)
print(a.dtype)

<class 'list'>
[[ 3  8  9]
 [ 1 -7  0]
 [ 4 12  4]]
int8


In [90]:
#assign colname(structured datatype)
dt=np.dtype([('density','i4')])
print(dt)
#assign values to the col named density
x=np.array([(393,),(337,),(256,)],dtype=dt)#similar to np.array([393,337,256],dtype=dt)
print(x)
print(x['density'])
print(x['density'][1])#similar to print(x[1])

[('density', '<i4')]
[(393,) (337,) (256,)]
[393 337 256]
(337,)
337


In [96]:
#1 level drill down
e={'hydrogen':1,'helium':2,'carbon':6}
e['carbon']

6

In [100]:
#2 level drill down
e1={'hydrogen':{'number':1,'weight':1.007,'symbol':'H'},
   'helium':{'number':2,'weight':4.002,'symbol':'He'}}
print(e1)
#retrieve H

{'hydrogen': {'number': 1, 'weight': 1.007, 'symbol': 'H'}, 'helium': {'number': 2, 'weight': 4.002, 'symbol': 'He'}}


'H'

In [103]:
#3 level drill down
e2={'hydrogen':{'number':1,'weight':1.007,'symbol':'H'},
   'helium':{'number':2,'weight':4.002,'symbol':{'hydrogen':'H','helium':'He','carbon':'c'}}}
print(e2)
#retrieve C

{'hydrogen': {'number': 1, 'weight': 1.007, 'symbol': 'H'}, 'helium': {'number': 2, 'weight': 4.002, 'symbol': {'hydrogen': 'H', 'helium': 'He', 'carbon': 'c'}}}


'c'

In [104]:
#USECASE
'''country-string;density,i4;area,i4,population,i4
('Netherlands',393,82374,7698323),
('Belgium',2332,43543,43532)
('United Kingdom',324,45645,23453245)
('Germany',34,3456,2345)
('Italy',393,82374,7698323),
('Switzerland',2332,43543,43532)
('France',324,45645,23453245)
('Austria',34,3456,2345)
('Greece',393,82374,7698323),
('Ireland',2332,43543,43532)
('India',324,45645,23453245)
('Finland',34,3456,2345)
('Norway',393,82374,7698323)
#select 0th till 3rd ind row
select 4th row till  last
select population col
extract area col
extract country col
extract 0th till 4th row of country col 
0th till 11th row with 3 intervals from country col and 2nd till 8th row with 2 intervals from area col '''


"country-string;density,i4;area,i4,population,i4\n('Netherlands',393,82374,7698323),\n('Belgium',2332,43543,43532)\n('United Kingdom',324,45645,23453245)\n('Germany',34,3456,2345)\n('Italy',393,82374,7698323),\n('Switzerland',2332,43543,43532)\n('France',324,45645,23453245)\n('Austria',34,3456,2345)\n('Greece',393,82374,7698323),\n('Ireland',2332,43543,43532)\n('India',324,45645,23453245)\n('Finland',34,3456,2345)\n('Norway',393,82374,7698323)\n#select 0th till 3rd ind row\nselect 4th row till  last\nselect population col\nextract area col\nextract country col\nextract 0th till 4th row of country col \n0th till 11th row with 3 intervals from country col and 2nd till 8th row with 2 intervals from area col "

In [6]:
dt=np.dtype([('country','U13'),('density','i4'),('area','i4'),('population','i4')])
population=np.array([('Netherlands',393,82374,7698323),
('Belgium',2332,43543,43532),
('United Kingdom',324,45645,23453245),
('Germany',34,3456,2345),
('Italy',393,82374,7698323),
('Switzerland',2332,43543,43532),
('France',324,45645,23453245),
('Austria',34,3456,2345),
('Greece',393,82374,7698323),
('Ireland',2332,43543,43532),
('India',324,45645,23453245),
('Finland',34,3456,2345),
('Norway',393,82374,7698323)],dtype=dt)

print(population)
print(lis4[4:])

[('Netherlands',  393, 82374,  7698323) ('Belgium', 2332, 43543,    43532)
 ('United Kingdo',  324, 45645, 23453245)
 ('Germany',   34,  3456,     2345) ('Italy',  393, 82374,  7698323)
 ('Switzerland', 2332, 43543,    43532) ('France',  324, 45645, 23453245)
 ('Austria',   34,  3456,     2345) ('Greece',  393, 82374,  7698323)
 ('Ireland', 2332, 43543,    43532) ('India',  324, 45645, 23453245)
 ('Finland',   34,  3456,     2345) ('Norway',  393, 82374,  7698323)]
[('Italy',  393, 82374,  7698323) ('Switzerland', 2332, 43543,    43532)
 ('France',  324, 45645, 23453245) ('Austria',   34,  3456,     2345)
 ('Greece',  393, 82374,  7698323) ('Ireland', 2332, 43543,    43532)
 ('India',  324, 45645, 23453245) ('Finland',   34,  3456,     2345)
 ('Norway',  393, 82374,  7698323)]


In [9]:
#save the structured arry to a file
head="country density area population"
np.savetxt("D:/Trainings/Online Python/pop.csv",population,fmt="%s;%d;%d;%d",delimiter=";",header=head)

In [10]:
np.loadtxt("D:/Trainings/Online Python/pop.csv",delimiter=";",dtype=str)

array([['Netherlands', '393', '82374', '7698323'],
       ['Belgium', '2332', '43543', '43532'],
       ['United Kingdo', '324', '45645', '23453245'],
       ['Germany', '34', '3456', '2345'],
       ['Italy', '393', '82374', '7698323'],
       ['Switzerland', '2332', '43543', '43532'],
       ['France', '324', '45645', '23453245'],
       ['Austria', '34', '3456', '2345'],
       ['Greece', '393', '82374', '7698323'],
       ['Ireland', '2332', '43543', '43532'],
       ['India', '324', '45645', '23453245'],
       ['Finland', '34', '3456', '2345'],
       ['Norway', '393', '82374', '7698323']], dtype='<U13')

In [11]:
#Nested datatypes
dt=np.dtype([('time',[('hr',int),('min',int),('sec',int)]),('temp',float)])
time_temp=np.array([((11,12,13),23.8),((12,1,35),32.1),((12,19,60),21.32)],dtype=dt)
print(time_temp)

[((11, 12, 13), 23.8 ) ((12,  1, 35), 32.1 ) ((12, 19, 60), 21.32)]


In [18]:
print(time_temp['time'])#time col alone
print(time_temp[:])#entire array
print(time_temp[:2])#first 2 rows
print(time_temp[1:])#from 1st ind to last
print(time_temp[:-1])
print(time_temp['time']['hr'])
print(time_temp['temp'])

[(11, 12, 13) (12,  1, 35) (12, 19, 60)]
[((11, 12, 13), 23.8 ) ((12,  1, 35), 32.1 ) ((12, 19, 60), 21.32)]
[((11, 12, 13), 23.8) ((12,  1, 35), 32.1)]
[((12,  1, 35), 32.1 ) ((12, 19, 60), 21.32)]
[((11, 12, 13), 23.8) ((12,  1, 35), 32.1)]
[11 12 12]
[23.8  32.1  21.32]


In [21]:
#array slicing - slice 4x4 matrix to 4 equal parts
xs=np.arange(16)
xs=xs.reshape(4,4)
print(xs)
print("top left",xs[:2,:2])
print("top right",xs[:2,2:])
print("bottom left",xs[2:,:2])
print("bootom right",xs[2:,2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
top left [[0 1]
 [4 5]]
top right [[2 3]
 [6 7]]
bottom left [[ 8  9]
 [12 13]]
bootom right [[10 11]
 [14 15]]


In [34]:
xs=np.arange(16)
xs=xs.reshape(4,4)
print(xs)
u_half=np.hsplit(np.vsplit(xs,2)[0],2)
#print(u_half)
l_half=np.hsplit(np.vsplit(xs,2)[1],2)
#print(l_half)
print("\n Upper left : ")
u_left=u_half[0]
print(u_left)

print("\n lower left : ")
l_left=l_half[0]
print(l_left)

print("\n Upper right : ")
u_right=u_half[1]
print(u_right)

print("\n lower right : ")
l_right=l_half[1]
print(l_right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 Upper left : 
[[0 1]
 [4 5]]

 lower left : 
[[ 8  9]
 [12 13]]

 Upper right : 
[[2 3]
 [6 7]]

 lower right : 
[[10 11]
 [14 15]]


Numerial operations


In [39]:
inp=[20.1,20.8,21.9,22.5,22.7,22.3,21.8,21.2]
print(type(inp))
#convert the values to 1D array
out=np.array(inp)
print(out)
print(type(out))
print(out+2)
print(out-2)
print(out*2)
print(out/2)

<class 'list'>
[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2]
<class 'numpy.ndarray'>
[22.1 22.8 23.9 24.5 24.7 24.3 23.8 23.2]
[18.1 18.8 19.9 20.5 20.7 20.3 19.8 19.2]
[40.2 41.6 43.8 45.  45.4 44.6 43.6 42.4]
[10.05 10.4  10.95 11.25 11.35 11.15 10.9  10.6 ]


In [47]:
#arithmetic operations with 2 arrays
arr1=np.array([(1,2,3),(4,5,6),(7,8,9)])#2D
print(arr1)
arr2=np.ones((3,3))#2D
print(arr2)
print(arr1+arr2)
np.add(arr1,arr2)
print(np.subtract(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.divide(arr1,arr2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [48]:
print(np.dot(arr1,arr2))

[[ 6.  6.  6.]
 [15. 15. 15.]
 [24. 24. 24.]]


comparison operator

In [42]:
a=np.array([(11,12,13),(21,22,23),(31,32,33)])
b=np.array([(11,102,13),(201,22,203),(31,32,303)])
print(a==b) #compares each and every ele n returns boolean output
print(np.array_equal(a,b))#gives only one end result -boolean output
print(np.array_equal(a,a))

[[ True False  True]
 [False  True False]
 [ True  True False]]
False
True


Logical operator

In [44]:
print(bool(0))#bool output of 0 is true
print(bool(88))#bool output of value other than 0 is true

False
True


In [ ]:
a=[1,3,False,4] #boolean output of this is True,True,False,True
b=[3,0,True,False] #boolean output of this is True,False,True,False
print(np.logical_not(a))
print(np.logical_not(b))
print(np.logical_or(a,b))
print(np.logical_and(a,b))

In [50]:
#3Darray -3matrices 3x3 (both the arrays)
X = np.array( [[(3, 1, 2),
                (4, 2, 2),
                (2, 4, 1)],
               
               [(3, 2, 2),
                (4, 4, 3),
                (4, 1, 1)],
               
               [(2, 2, 1),
                (3, 1, 3),
                (3, 2, 3)]])

Y = np.array( [[(2, 3, 1),
                (2, 2, 4),
                (3, 4, 4)],
               
               [(1, 4, 1),
                (4, 1, 2),
                (4, 1, 2)],
               
               [(1, 2, 3),
                (4, 1, 1),
                (3, 1, 4)]])

print("\n Dot product:",np.dot(X,Y))
print("\n Addition:",np.add(X,Y))
print("\n Subtraction:",np.subtract(X,Y))
print("\n Multiplication:",np.multiply(X,Y))
print("\n Division:",np.divide(X,Y))


 Dot product: [[[[14 19 15]
   [15 15  9]
   [13  9 18]]

  [[18 24 20]
   [20 20 12]
   [18 12 22]]

  [[15 18 22]
   [22 13 12]
   [21  9 14]]]


 [[[16 21 19]
   [19 16 11]
   [17 10 19]]

  [[25 32 32]
   [32 23 18]
   [29 15 28]]

  [[13 18 12]
   [12 18  8]
   [11 10 17]]]


 [[[11 14 14]
   [14 11  8]
   [13  7 12]]

  [[17 23 19]
   [19 16 11]
   [16 10 22]]

  [[19 25 23]
   [23 17 13]
   [20 11 23]]]]

 Addition: [[[5 4 3]
  [6 4 6]
  [5 8 5]]

 [[4 6 3]
  [8 5 5]
  [8 2 3]]

 [[3 4 4]
  [7 2 4]
  [6 3 7]]]

 Subtraction: [[[ 1 -2  1]
  [ 2  0 -2]
  [-1  0 -3]]

 [[ 2 -2  1]
  [ 0  3  1]
  [ 0  0 -1]]

 [[ 1  0 -2]
  [-1  0  2]
  [ 0  1 -1]]]

 Multiplication: [[[ 6  3  2]
  [ 8  4  8]
  [ 6 16  4]]

 [[ 3  8  2]
  [16  4  6]
  [16  1  2]]

 [[ 2  4  3]
  [12  1  3]
  [ 9  2 12]]]

 Division: [[[1.5        0.33333333 2.        ]
  [2.         1.         0.5       ]
  [0.66666667 1.         0.25      ]]

 [[3.         0.5        2.        ]
  [1.         4.         1.5       

In [54]:
#3Darray -3matrices 3x3 - x-3,3,3;y-2,3,3 (dot alone works)
X = np.array( [[(3, 1, 2),
                (4, 2, 2),
                (2, 4, 1)],
               
               [(3, 2, 2),
                (4, 4, 3),
                (4, 1, 1)],
               
               [(2, 2, 1),
                (3, 1, 3),
                (3, 2, 3)]])

Y = np.array( [[(2, 3, 1),
                (2, 2, 4),
                (3, 4, 4)],
               
               [(1, 4, 1),
                (4, 1, 2),
                (4, 1, 2)]])

print("\n Dot product:",np.dot(X,Y))
print("\n Addition:",np.add(X,Y))
print("\n Subtraction:",np.subtract(X,Y))
print("\n Multiplication:",np.multiply(X,Y))
print("\n Division:",np.divide(X,Y))


 Dot product: [[[[14 19 15]
   [15 15  9]]

  [[18 24 20]
   [20 20 12]]

  [[15 18 22]
   [22 13 12]]]


 [[[16 21 19]
   [19 16 11]]

  [[25 32 32]
   [32 23 18]]

  [[13 18 12]
   [12 18  8]]]


 [[[11 14 14]
   [14 11  8]]

  [[17 23 19]
   [19 16 11]]

  [[19 25 23]
   [23 17 13]]]]


ValueError: operands could not be broadcast together with shapes (3,3,3) (2,3,3) 

In [52]:
#3Darray -with 2 D - x-3,3,3;y-2D 
X = np.array( [[(3, 1, 2),
                (4, 2, 2),
                (2, 4, 1)],
               
               [(3, 2, 2),
                (4, 4, 3),
                (4, 1, 1)],
               
               [(2, 2, 1),
                (3, 1, 3),
                (3, 2, 3)]])

Y = np.array( [[(2, 3, 1),
                (2, 2, 4),
                (3, 4, 4)]])

print("\n Dot product:",np.dot(X,Y))
print("\n Addition:",np.add(X,Y))
print("\n Subtraction:",np.subtract(X,Y))
print("\n Multiplication:",np.multiply(X,Y))
print("\n Division:",np.divide(X,Y))


 Dot product: [[[[14 19 15]]

  [[18 24 20]]

  [[15 18 22]]]


 [[[16 21 19]]

  [[25 32 32]]

  [[13 18 12]]]


 [[[11 14 14]]

  [[17 23 19]]

  [[19 25 23]]]]

 Addition: [[[5 4 3]
  [6 4 6]
  [5 8 5]]

 [[5 5 3]
  [6 6 7]
  [7 5 5]]

 [[4 5 2]
  [5 3 7]
  [6 6 7]]]

 Subtraction: [[[ 1 -2  1]
  [ 2  0 -2]
  [-1  0 -3]]

 [[ 1 -1  1]
  [ 2  2 -1]
  [ 1 -3 -3]]

 [[ 0 -1  0]
  [ 1 -1 -1]
  [ 0 -2 -1]]]

 Multiplication: [[[ 6  3  2]
  [ 8  4  8]
  [ 6 16  4]]

 [[ 6  6  2]
  [ 8  8 12]
  [12  4  4]]

 [[ 4  6  1]
  [ 6  2 12]
  [ 9  8 12]]]

 Division: [[[1.5        0.33333333 2.        ]
  [2.         1.         0.5       ]
  [0.66666667 1.         0.25      ]]

 [[1.5        0.66666667 2.        ]
  [2.         2.         0.75      ]
  [1.33333333 0.25       0.25      ]]

 [[1.         0.66666667 1.        ]
  [1.5        0.5        0.75      ]
  [1.         0.5        0.75      ]]]


In [56]:
#3D with 1D
X = np.array( [[(3, 1, 2),
                (4, 2, 2),
                (2, 4, 1)],
               
               [(3, 2, 2),
                (4, 4, 3),
                (4, 1, 1)],
               
               [(2, 2, 1),
                (3, 1, 3),
                (3, 2, 3)]])

Y = np.array( [2, 3, 1])

print("\n Dot product:",np.dot(X,Y))
print("\n Addition:",np.add(X,Y))
print("\n Subtraction:",np.subtract(X,Y))
print("\n Multiplication:",np.multiply(X,Y))
print("\n Division:",np.divide(X,Y))


 Dot product: [[11 16 17]
 [14 23 12]
 [11 12 15]]

 Addition: [[[5 4 3]
  [6 5 3]
  [4 7 2]]

 [[5 5 3]
  [6 7 4]
  [6 4 2]]

 [[4 5 2]
  [5 4 4]
  [5 5 4]]]

 Subtraction: [[[ 1 -2  1]
  [ 2 -1  1]
  [ 0  1  0]]

 [[ 1 -1  1]
  [ 2  1  2]
  [ 2 -2  0]]

 [[ 0 -1  0]
  [ 1 -2  2]
  [ 1 -1  2]]]

 Multiplication: [[[ 6  3  2]
  [ 8  6  2]
  [ 4 12  1]]

 [[ 6  6  2]
  [ 8 12  3]
  [ 8  3  1]]

 [[ 4  6  1]
  [ 6  3  3]
  [ 6  6  3]]]

 Division: [[[1.5        0.33333333 2.        ]
  [2.         0.66666667 2.        ]
  [1.         1.33333333 1.        ]]

 [[1.5        0.66666667 2.        ]
  [2.         1.33333333 3.        ]
  [2.         0.33333333 1.        ]]

 [[1.         0.66666667 1.        ]
  [1.5        0.33333333 3.        ]
  [1.5        0.66666667 3.        ]]]


In [59]:
#collapsing of arrays
e=np.array([(1,2,3),(4,5,6)])
print(e)
print(e.ndim)
print(e.shape)
print(e.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [61]:
print(e.flatten())
print(e.flatten().ndim)

[1 2 3 4 5 6]
1


In [62]:
print(np.ravel(e))#e.ravel()

[1 2 3 4 5 6]


In [63]:
print(e.reshape(1,6))

[[1 2 3 4 5 6]]


In [66]:
#hstack and vstack
f=np.array([1,2,3])#1D
g=np.array([4,5,6])#1D
print(f)
print(g)
print("horizontal append: ",np.hstack((f,g)))
print("vertical append: ",np.vstack((f,g)))

[1 2 3]
[4 5 6]
horizontal append:  [1 2 3 4 5 6]
vertical append:  [[1 2 3]
 [4 5 6]]


In [67]:
#matmul, matric product of 2 arrays
h=np.array([(1,2),(3,4)])
i=np.array([(5,6),(7,8)])
print(h)
print(i)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [68]:
print(np.matmul(h,i))

[[19 22]
 [43 50]]


In [69]:
print(np.dot(h,i))

[[19 22]
 [43 50]]


In [70]:
print(np.multiply(h,i))

[[ 5 12]
 [21 32]]


In [1]:
#USECASE
'''dtype=np.dtype([('density','float'),('volume','i4')])
(393.1,25),(337,2342),(256.2,4353)
retrieve density col
retrieve volume col
extract 0 till 2 ind row with 2 int from density 
retrieve 0 ind col from the array'''

"dtype=np.dtype([('density','float'),('volume','i4')])\n(393.1,25),(337,2342),(256.2,4353)\nretrieve density col\nretrieve volume col\nextract 0 till 2 ind row with 2 int from density \nretrieve 0 ind col from the array"

In [2]:
#USECASE
'''create a dataset with cols 'name' (alpha,beta,gamma,delta), 'age' (23,45,12,65),'marks' (34.54,89.3,98.23,99)
extract gamma's age
marks from 0th till last with 2 intervals; age from 0th till last with 2 intervals- single line command'''

"create a dataset with cols 'name' (alpha,beta,gamma,delta), 'age' (23,45,12,65),'marks' (34.54,89.3,98.23,99)\nextract gamma's age\nmarks from 0th till last with 2 intervals; age from 0th till last with 2 intervals- single line command"