Map,Reducer,Accumulator,Numpy

In [1]:
numbers=[1,2,3,4,5,6,7,9,10,14]
list(map(lambda x:x%3==0,numbers))

[False, False, True, False, False, True, False, True, False, False]

In [2]:
numbers=[1,2,3,4,5,6,7,9,10,14]
list(filter(lambda x:x%3==0,numbers))

[3, 6, 9]

Arithmetic operations in filter and map

In [4]:
varlist=[0,10,0,30,1]
out=list(filter(lambda var:var*10,varlist))
print("values are : ",out)

values are :  [10, 30, 1]


In [5]:
varlist=[0,10,0,30,1]
out=list(map(lambda var:var*10,varlist))
print("values are : ",out)

values are :  [0, 100, 0, 300, 10]


In [7]:
#direct sequence
list(map(lambda x:x*5,[1,2,34]))

[5, 10, 170]

In [11]:
#iteration over dict
dict_a=[{'name':'python','points':10},{'name':'java','points':8}]
type(dict_a)
print(dict_a)
print(list(map(lambda x:x['name'],dict_a)))
print(list(map(lambda x:x['points']*10,dict_a)))
print(list(map(lambda x:x['name']=='python',dict_a)))

[{'name': 'python', 'points': 10}, {'name': 'java', 'points': 8}]
['python', 'java']
[100, 80]
[True, False]


In [1]:
#usecase add the 2 lists 
#iteration over list
list_a =[1,2,3]
list_b=[4,5,6]

In [14]:
import operator as o
list_a =[1,2,3]
list_b=[4,5,6]
print(list(map(o.add,list_a,list_b)))

[5, 7, 9]


Reducer

In [1]:
import functools as f
li=[5,8,10,20,50,100]
sum=f.reduce((lambda x,y:x+y),li)
print(sum)#(5+8=13,13+10=23,23+20...)

193


In [32]:
#maximum ele 
lis=[3,45,254,76,989]
print("The maximum element of the list is : ",end="\t")
print(f.reduce(lambda a,b: a if a>b else b,lis))

The maximum element of the list is : 	989


In [2]:
#usecase
list_a=[1,2,300,4,5]
list_b=[10,20,30]
#retrieve max ele using map func

Accumulator

In [37]:
import itertools as i
#create a list
lis=[1,3,4,10,4]
print("The summation of list is : ",end="")
print(list(i.accumulate(lis,lambda x,y:x+y)))
print(f.reduce(lambda x,y:x+y,lis))

The summation of list is : [1, 4, 8, 18, 22]
22


In [ ]:
#usecase
li=[1,0,5,50,99]
#perform * using reduce and accumulator

In [ ]:
#USECASE
#create a 1D array of 30 evenly spaced elements bet 2.5 and 6.5, including end val 

In [42]:
'''Difference between reduce and accumulate
reduce() is defined in "functools" module, accumulate() in "itertools" module
reduce() stores the intermediate results and returns only final output
accumulate() returns a list with intermediate results. The last element in the list is the final output
sequence is passed after the func(lambda) in reducer, whereas its passed b4 the func in accumulator'''

'Difference between reduce and accumulate\nreduce() is defined in "functools" module, accumulate() in "itertools" module\nreduce() stores the intermediate results and returns only final output\naccumulate() returns a list with intermediate results. The last element in the list is the final output\nsequence is passed after the func(lambda) in reducer, whereas its passed b4 the func in accumulator'

NUMPY - Numerical Python

In [43]:
'''Array:collection of data items of same type
Matrix: rectangle of nos., arranged in rows and cols
Dimension: measurable extent of particular kind like length, breadth (matrix,rows and cols)
shape: count of rows and cols (if its 1D array - count of elements)
size : count of elements in an array
Reshape: resizing the array
Datatype : type of the data(str, int, float,..)
Itemsize : no. of bytes consumed by single element in an array
nbytes:no. of bytes consumed by all the elements in an array

col refers to axis 0
row refers to axis 1'''

'Array:collection of data items of same type\nMatrix: rectangle of nos., arranged in rows and cols\nDimension: measurable extent of particular kind like length, breadth (matrix,rows and cols)\nshape: count of rows and cols (if its 1D array - count of elements)\nsize : count of elements in an array\nReshape: resizing the array\nDatatype : type of the data(str, int, float,..)\nItemsize : no. of bytes consumed by single element in an array\nnbytes:no. of bytes consumed by all the elements in an array\n\ncol refers to axis 0\nrow refers to axis 1'

In [5]:
import numpy as np
tu=(1,2,3)
type(tu)
out_tu=np.array(tu)
type(out_tu)
print(out_tu.ndim) # 1-single dim,1 rank array
print(out_tu.shape) #count of elements since its 1 D
print(out_tu.size) #count of elements
print(out_tu.dtype)
print(out_tu.itemsize)#no.of bytes consumed by single ele
print(out_tu.nbytes) #total no. of bytes consumed

1
(3,)
3
int32
4
12


In [6]:
#create an array with range
my_array=np.arange(9)# 0 to 8
print(my_array)
#usecase - chk for ndim,shape,size,dtype,itemsize,nbytes,sum

[0 1 2 3 4 5 6 7 8]


In [7]:
print(len(my_array))
print(type(my_array))

9
<class 'numpy.ndarray'>


In [9]:
#change the data type of my_array
print(my_array.astype(str))
print(my_array.astype(int))
print(my_array.astype(float))

['0' '1' '2' '3' '4' '5' '6' '7' '8']
[0 1 2 3 4 5 6 7 8]
[0. 1. 2. 3. 4. 5. 6. 7. 8.]


In [59]:
print(np.arange(10))#0 to 9
print(np.arange(1,15))#1 to 14
print(np.arange(1,15,3))#1 to 14 with 3 int

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  4  7 10 13]


Linespace

start : starting val of the seq; stop-end val of the seq; num=no.of samples to be generated(default=50);
endpoint:true by default-stop val will be included, if false then stop val will nt be included

In [68]:
np.linspace(1,5,num=5)

array([1., 2., 3., 4., 5.])

In [66]:
np.linspace(1,5,endpoint=False)

array([1.  , 1.08, 1.16, 1.24, 1.32, 1.4 , 1.48, 1.56, 1.64, 1.72, 1.8 ,
       1.88, 1.96, 2.04, 2.12, 2.2 , 2.28, 2.36, 2.44, 2.52, 2.6 , 2.68,
       2.76, 2.84, 2.92, 3.  , 3.08, 3.16, 3.24, 3.32, 3.4 , 3.48, 3.56,
       3.64, 3.72, 3.8 , 3.88, 3.96, 4.04, 4.12, 4.2 , 4.28, 4.36, 4.44,
       4.52, 4.6 , 4.68, 4.76, 4.84, 4.92])

In [67]:
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [71]:
#temperature in celsius
cvalues=[20.1,20.8,21.9,22.5,22.7,22.3,21.8,21.2]
c=np.array(cvalues) #convert list to array
print(c)
print(c*9/5+32) #convert celsius to fahrenheit
print(type(c))

[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2]
[68.18 69.44 71.42 72.5  72.86 72.14 71.24 70.16]
<class 'numpy.ndarray'>


In [72]:
fvalues=[x*9/5+32 for x in cvalues]
print(fvalues)

[68.18, 69.44, 71.42, 72.5, 72.86, 72.14, 71.24000000000001, 70.16]


In [74]:
#memory in list
import sys
s=range(1000)
print(sys.getsizeof(7)*len(s))

14000


In [75]:
#memory in array
d=np.array(1000)
print(d.nbytes)

4


In [77]:
#Finding min, max,mean,median,std
data=np.array([(10,23,1,4,5,3,2,6)])
min=np.min(data) #min of data
print(min)

1


In [78]:
max=np.max(data) #max of data
print(max)

23


In [81]:
a=np.array([1,2,3,4,5])
mean=np.mean(a)
print(mean)
a.mean()

3.0


3.0

In [85]:
median=np.median(a)
print(median)
a.median()#err - no attribute median

3.0


AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [87]:
std=np.std(a)
print(std)
a.std()

1.4142135623730951


1.4142135623730951

2 dimensional, 2 rank array

In [89]:
#2Darray
arr_2 =np.array([(1,2,3),(4,5,6)])
print(arr_2)
print(arr_2.shape)
print(arr_2.size)
print(arr_2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [3]:
#Arithmetic operations in 2 D array
x=np.ones((3,4))
print(x)
#print(x.shape)
#print(x.ndim)
y=np.arange(4)
print(y)
#print(y.shape)
#print(y.ndim)
#add x n y
out=x+y 
print(out)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [5]:
print(np.add(x,y))

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [13]:
#dot product
f=np.array([(1,2),(3,4)]) #2 D
print("f",f)
g=np.array([4,5]) #1 D
print("g",g)
print(np.dot(f,g)) #1*4+2*5

f [[1 2]
 [3 4]]
g [4 5]
[14 32]


In [106]:
print(np.add(f,g))
print(np.subtract(f,g))
print(np.multiply(f,g))
print(np.divide(f,g))

[5 7]
[-3 -3]
[ 4 10]
[0.25 0.4 ]


In [107]:
#assign dimension to 1D
a=np.array([1,2,3,4,5])
print(a)
print(a.ndim)#1D
print(a.shape)#count of elements

[1 2 3 4 5]
1
(5,)


In [108]:
#assign dimension to 1D
a=np.array([1,2,3,4,5],ndmin=2)
print(a)
print(a.ndim)#1D
print(a.shape)#count of elements

[[1 2 3 4 5]]
2
(1, 5)


In [109]:
#assign dimension to 1D
a=np.array([1,2,3,4,5],ndmin=3)
print(a)
print(a.ndim)#1D
print(a.shape)#count of elements

[[[1 2 3 4 5]]]
3
(1, 1, 5)


In [111]:
#reshaping
a=np.array([(1,2,3),(4,5,6)])
print(a)
b=a.reshape(3,2)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


Dataslicing in 1D

In [135]:
a=np.arange(10)
print(a)
print(a[5])
print(a[2:])
print(a[2:5])
print(a[2:7:2])

[0 1 2 3 4 5 6 7 8 9]
5
[2 3 4 5 6 7 8 9]
[2 3 4]
[2 4 6]


In [143]:
s=np.array([(1,2,3,4),(2,3,7,4),(8,3,65,74)])
print("Sum of cols : ",s.sum(axis=0))
print("sum of rows : ",s.sum(axis=1))
print("Sq.root : ",np.sqrt(s))
print("std deviation : ",np.std(s))

Sum of cols :  [11  8 75 82]
sum of rows :  [ 10  16 150]
Sq.root :  [[1.         1.41421356 1.73205081 2.        ]
 [1.41421356 1.73205081 2.64575131 2.        ]
 [2.82842712 1.73205081 8.06225775 8.60232527]]
std deviation :  24.665540514833424


In [144]:
#3D array
a=np.arange(24)
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [150]:
#dtype parameter
a=np.array([1,2,3],dtype=float)
print(a)
print(a.dtype)

[1. 2. 3.]
float64


In [151]:
#numpy - to create array using funciton
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [152]:
a=np.zeros((2,2),dtype=int)
print(a)

[[0 0]
 [0 0]]


In [153]:
b=np.ones((1,2))
print(b)

[[1. 1.]]


In [154]:
b=np.ones((1,2),dtype=int)
print(b)

[[1 1]]


In [156]:
c=np.full((2,2),10)
print(c)

[[10 10]
 [10 10]]


In [157]:
d=np.eye(2,dtype=int)
print(d)

[[1 0]
 [0 1]]


In [158]:
d=np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
e=np.random.random((2,2))
print(e)

[[0.9411934  0.00529744]
 [0.17111266 0.94900775]]


In [160]:
a=np.arange(5) #0 to 4
print(a)

[0 1 2 3 4]


In [165]:
#convert list to 3x3 matrix
a=np.arange(18)
print(a.ndim)
#reshape
b=a.reshape(2,3,3)
print(b)
print(b.ndim)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
3


In [1]:
#diagonal elements
a=np.arange(9)
b=a.reshape(3,3)
print(b)
print("Diagonal",b.diagonal(0)) #b.diagonal()
print("Diagonal",b.diagonal(-1)) #lower diagonal
print("Diagonal",b.diagonal(1))  #upper diagonal

NameError: name 'np' is not defined

In [174]:
print(np.fliplr(b))

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [175]:
print("Reversed diagonal : ",np.fliplr(b).diagonal())

Reversed diagonal :  [2 4 6]
