In [2]:
a=10
b=10.56
c="akjsb"
d=complex(2)

In [3]:
type(a)

int

In [4]:
type(b)

float

In [5]:
type(c)

str

In [6]:
type(d)

complex

In [7]:
a,b,c=1,2.5,"sdbj"
print(a)
print(b)
print(c)

1
2.5
sdbj


In [8]:
a=b=c=5
print(a);print(b);print(c)

5
5
5


In [9]:
a=5
def func1():
    a=10
    print('inside func1=',a)
def func2():
    print('inside func2=',a)
func1()
func2()

inside func1= 10
inside func2= 5


In [10]:
def func1():
    global a
    a=15
    print('Inside func1=',a)
def func2():
    print('inside func2=',a)
func1()
func2()

Inside func1= 15
inside func2= 15


# Data  Types

In [11]:
x=1
y=2.5
z=2+3j

In [12]:
type(x)

int

In [13]:
type(y)

float

In [14]:
type(z)

complex

In [15]:
a=True

In [16]:
type(a)

bool

In [17]:
a=-5j

In [18]:
a

(-0-5j)

#  Strings

In [19]:
print("strings are\nimmutable")

strings are
immutable


In [20]:
print('string are \\ immutable')

string are \ immutable


In [21]:
print('string are \t immutable')

string are 	 immutable


In [22]:
print('string are \' immutable\'')

string are ' immutable'


In [23]:
print('string are \" immutable\"')

string are " immutable"


In [24]:
str1="ashok Karthik"

In [25]:
print(str1[2:8])

hok Ka


In [26]:
print(str1[-3:])

hik


In [27]:
print(str1[::-1])

kihtraK kohsa


In [28]:
Strr1=' Hello, World '

In [29]:
Strr1[1]='h'

TypeError: 'str' object does not support item assignment

In [30]:
print(Strr1.count('l'))

3


In [31]:
len(Strr1)

14

In [32]:
print(Strr1.strip())

Hello, World


In [33]:
print(Strr1.lower())

 hello, world 


In [34]:
print(Strr1.upper())

 HELLO, WORLD 


In [35]:
print(Strr1.split(','))

[' Hello', ' World ']


In [36]:
print(Strr1.count('l'))

3


In [37]:
print(Strr1.replace('l','a'))

 Heaao, Worad 


In [38]:
str1="sjhbd"
str12="sjkbsjbsj"

In [39]:
str3=str1+str12
str3

'sjhbdsjkbsjbsj'

In [40]:
str3=str1*3
str3

'sjhbdsjhbdsjhbd'

In [41]:
str1.isalpha()

True

In [42]:
str1.isdigit()

False

In [43]:
str1="kjd3464"
a=[]
d=[]
for i in str1:
    if i.isalpha():
        a.append(i)
    elif i.isdigit():
        d.append(i)
print(a)
print(d)

['k', 'j', 'd']
['3', '4', '6', '4']


In [44]:
def func1(str5):
    global a
    a=[]
    global b
    b=[]
    for i in str5:
        if i.isalpha():
            a.append(i)
        elif i.isdigit():
            b.append(i)
    #print(a)
    #print(b)
    #for j in a:
        #print(j, end=' ')
    return a,b
x=func1(input("enter the string  :"))
print(' '.join(a))
print(' '.join(b))
            

enter the string  :kjfnjngd3d545 545fg4f
k j f n j n g d d f g f
3 5 4 5 5 4 5 4


To find length of a string

In [45]:
def funlk(str6):
    count=0
    for i in str6:
        count += 1
    return count
print(funlk("khbf f dkfjnjfndnkfjn"))

21


In [46]:
func1('google.com')

(['g', 'o', 'o', 'g', 'l', 'e', 'c', 'o', 'm'], [])

Write a Python program to count the number of characters (character frequency) in a string.

In [47]:
def numberofchar(str7):
    dict={}
    for i in str7:
        keys=dict.keys()
        if i in keys:
            dict[i] += 1
        else:
            dict[i] = 1
    return dict
        
print(numberofchar('google.com'))

{'g': 2, 'o': 3, 'l': 1, 'e': 1, '.': 1, 'c': 1, 'm': 1}


In [48]:
def skj(str8):
    dict1={}
    for i in str8:
        keys1=dict1.keys()
        if i in keys1:
            dict1[i]+=1
        else:
            dict1[i]=1
    return dict1
print(skj('ksjf3fs54 3s54f5d'))
    

{'k': 1, 's': 3, 'j': 1, 'f': 3, '3': 2, '5': 3, '4': 2, ' ': 1, 'd': 1}


#wap that accepts a sentence and calculates the number of letters and digits in sentence

In [49]:
def func6(st7):
    a=b=0
    for i in st7:
        if i.isalpha():
            a=a+1
        elif i.isdigit():
            b=b+1
    print('chracters',a)
    print('digits',b)
    return a,b
func6('kjb13s15s5f1s31f65sdf')
            

chracters 11
digits 10


(11, 10)

In [50]:
str1='kfb fkf'
str2='kjs sfknfkjnf '
if(len(str1)==len(str2)):
    print('strings are equal')
elif(len(str1)>len(str2)):
    print('str1 is greater')
else:
    print('str2 is greater')

str2 is greater


In [70]:
import functools
str8='kjafnkjs fiu24y3js98wr95409u3420492j4ifjks'
a=[]
b=[]
for i in str8:
    if i.isalpha():
        a.append(i)
    elif i.isdigit():
        b.append(int(i))
print(a)
print(b)
print(functools.reduce(lambda x,y:x+y,b))
newdig=' '.join(a)
print(newdig)


['k', 'j', 'a', 'f', 'n', 'k', 'j', 's', 'f', 'i', 'u', 'y', 'j', 's', 'w', 'r', 'u', 'j', 'i', 'f', 'j', 'k', 's']
[2, 4, 3, 9, 8, 9, 5, 4, 0, 9, 3, 4, 2, 0, 4, 9, 2, 4]
81
k j a f n k j s f i u y j s w r u j i f j k s


In [71]:
a={}
str9='ksjffs354ffbjnff354fs54fSdsa'
for i in str9:
    if i in a.keys():
        a[i]+=1
    else:
        a[i]=1
print(a)
    

{'k': 1, 's': 4, 'j': 2, 'f': 8, '3': 2, '5': 3, '4': 3, 'b': 1, 'n': 1, 'S': 1, 'd': 1, 'a': 1}


In [73]:
import pandas as pd
a={}
s=input('enter a sentence')
new=s.split(' ')
for i in new:
    if i in a.keys():
        a[i]+=1
    else:
        a[i]=1
print(a)
c=pd.Series(a)
print(c)
print(c.max())
print(c.min())


enter a sentenceASHOK ashok arun arun arun ashok
{'ASHOK': 1, 'ashok': 2, 'arun': 3}
ASHOK    1
ashok    2
arun     3
dtype: int64
3
1


Write a Python program to get a string made of the first 2 and the last 2 chars from a given a string. If the string length is less than 2, return instead of the empty string.

In [74]:
def funct1(strr):
    if len(strr)<=2:
        return ''
    else:
        return strr[:2]+strr[-2:]
print(funct1('ashokkarthik'))
print(funct1('as'))
print(funct1('asa'))
print(funct1('a'))

asik

assa



In [75]:
def funct(str1):
    char=str1[0]
    str1=str1.replace(char,'$')
    return str1
print(funct('asfhk salks ff dfl'))

$sfhk s$lks ff dfl


In [76]:
a=[]
def funct(str1):
    b=str1.split(' ')
    for i in b:
        char=i[0]
        i=i.replace(char,'$')
        a.append(i)
    return a
print(funct('askjh aks oirjt erkjn wekjrhwe lksehj'))

['$skjh', '$ks', '$irjt', '$rkjn', '$ekjrh$e', '$ksehj']


Write a Python program to get a single string from two given strings, separated by a space and swap the first two characters of each string.

In [77]:
def funct(a,b):
    newa=b[:2]+a[2:]
    newb=a[:2]+b[2:]
    print(newa,newb)
funct('abc','xyz')

xyc abz


 Write a Python program to add 'ing' at the end of a given string (length should be at least 3). If the given string already ends with 'ing' then add 'ly' instead. If the string length of the given string is less than 3, leave it unchanged

In [78]:
def funct(str1):
    if len(str1)<=3:
        return str1
    elif len(str1)>3:
        if str1[-3:]=='ing':
            str1=str1+'ly'
        else:
            str1=str1+'ing'
    return str1
print(funct('as'))
print(funct('ash'))
print(funct('ashing'))
print(funct('ashin'))


as
ash
ashingly
ashining


Write a Python function that takes a list of words and returns the length of the longest one

In [79]:
a=[]
def funct1(str1):
    for i in str1:
        a.append((len(i),i))
        a.sort()
    return a[-1][1]
print(funct1(['ashok','skjfs','sfbsjdfb']))
    

sfbsjdfb


In [80]:
#longest
a=[]
def funct1(str1):
    for i in str1:
        a.append((len(i),i))
        a.sort()
    return a[-1]
print(funct1(['ashok','skjfs','sfbsjdfb']))
    

(8, 'sfbsjdfb')


In [81]:
#smallest
a=[]
def funct1(str1):
    for i in str1:
        a.append((len(i),i))
        a.sort()
    return a[0]
print(funct1(['ashok','skjfs','sfbsjdfb']))
    

(5, 'ashok')


Write a Python program to remove the nth index character from a nonempty string.

In [82]:
def removestr(str1,n):
    right=str1[:n]
    left=str1[n+1:]
    return right+left
print(removestr('python',2))
print(removestr('python',0))
print(removestr('python',5))

pyhon
ython
pytho


Write a Python program to change a given string to a new string where the first and last chars have been exchanged.

In [83]:
def funct1(str1):
    return str1[-1]+str1[1:-1]+str1[0]
print(funct1('ashok'))

kshoa


Write a Python program to remove the characters which have odd index values of a given string.

In [84]:
def funct1(str1):
    result=""
    for i in range(len(str1)):
        if i%2==0:
            result=result+str1[i]
    return result
print(funct1('ashokkarthik'))
print(funct1('ashohik'))

ahkati
ahhk


Write a Python program to count the occurrences of each word in a given sentence.

In [90]:
def funct1(str9):  
    a={}
    for i in str9:
        if i in a.keys():
            a[i]+=1
        else:
            a[i]=1
    return a
print(funct1('jsbskaldnaslksafkn'))

{'j': 1, 's': 4, 'b': 1, 'k': 3, 'a': 3, 'l': 2, 'd': 1, 'n': 2, 'f': 1}


Write a Python program that accepts a comma separated sequence of words as input and prints the unique words in sorted form (alphanumerically).

In [91]:
def inputfunct(str1):
    lower=str1.lower()
    upper=str1.upper()
    return lower,upper
print(inputfunct('ashok'))
    

('ashok', 'ASHOK')


Write a Python program that accepts a comma separated sequence of words as input and prints the unique words in sorted form (alphanumerically).

In [93]:
items=input('input comma seperated words')
a=[word for word in items.split(',')]
print(",".join(sorted(a)))

input comma seperated wordsashok,ashok,123,123,jh
123,123,ashok,ashok,jh


In [94]:
items = input("Input comma separated sequence of words")
words = [word for word in items.split(",")]
print(",".join(sorted(list(set(words)))))

Input comma separated sequence of wordsskjbjn jnfd,mf, flksf,
, flksf,mf,skjbjn jnfd


 Write a Python function to get a string made of 4 copies of the last two characters of a specified string (length must be at least 2)

In [95]:
def funct(str1):
    if len(str1)<=2:
        return str1
    else:
        a=str1[-2:]
        str1=a*4
    return str1
print(funct('ashok'))
print(funct('skjnsnfk'))
print(funct('sd'))

okokokok
fkfkfkfk
sd


Write a Python function to get a string made of its first three characters of a specified string. If the length of the string is less than 3 then return the original string. Go to the editor
Sample function and result : 

In [96]:
def funct(str1):
    if len(str1)<=3:
        return str1
    else:
        str1=str1[:3]
    return str1
print(funct('as'))
print(funct('ashok'))

as
ash


Write a Python program to get the last part of a string before a specified character.

In [97]:
def funct(sre1):
    sre1=sre1.rsplit('/',1)[0]
    return sre1
print(funct('www.ashok/skj/kj'))

www.ashok/skj


Write a Python function to reverses a string if it's length is a multiple of 4

In [98]:
def funct(str1):
    if len(str1)%4==0:
        str1=''.join(reversed(str1))
    else:
        return str1
    return str1
print(funct('ashokash'))
print(funct('ash'))

hsakohsa
ash


Write a Python function to convert a given string to all uppercase if it contains at least 2 uppercase characters in the first 4 characters.

In [99]:
def funct(str1):
    up=0
    for letter in str1[:4]:
        if letter.upper()==letter:
            up+=1
    if up>=2:
        return str1.upper()
    return str1
print(funct('sJUksnmn'))
print(funct('dfdggdh'))
    
            
        

SJUKSNMN
dfdggdh


Write a Python program to sort a string lexicographically.

In [100]:
def lexogical(str1):
    return sorted(str1)
print(lexogical('kjbfbajajsk'))
print(lexogical('karthik'))

['a', 'a', 'b', 'b', 'f', 'j', 'j', 'j', 'k', 'k', 's']
['a', 'h', 'i', 'k', 'k', 'r', 't']


Write a Python program to remove a newline in Python.

In [101]:
str1='Python Exercises\n'
print(str1)
print(str1.rstrip())

Python Exercises

Python Exercises


Write a Python program to check whether a string starts with specified characters.

In [102]:
str1='ashokkjshfnjn'
str1.startswith('ash')

True

Write a Python program to display formatted text (width=50) as output.

In [103]:
import textwrap

In [104]:
sample_text = '''
  Python is a widely used high-level, general-purpose, interpreted,
  dynamic programming language. Its design philosophy emphasizes
  code readability, and its syntax allows programmers to express
  concepts in fewer lines of code than possible in languages such
  as C++ or Java.
  '''

In [105]:
sample_text

'\n  Python is a widely used high-level, general-purpose, interpreted,\n  dynamic programming language. Its design philosophy emphasizes\n  code readability, and its syntax allows programmers to express\n  concepts in fewer lines of code than possible in languages such\n  as C++ or Java.\n  '

In [106]:
print(textwrap.fill(sample_text,width=50))

   Python is a widely used high-level, general-
purpose, interpreted,   dynamic programming
language. Its design philosophy emphasizes   code
readability, and its syntax allows programmers to
express   concepts in fewer lines of code than
possible in languages such   as C++ or Java.


Write a Python program to remove existing indentation from all of the lines in a given text.

In [107]:
text_wrap_without_indent=print(textwrap.dedent(sample_text))
text_wrap_without_indent


Python is a widely used high-level, general-purpose, interpreted,
dynamic programming language. Its design philosophy emphasizes
code readability, and its syntax allows programmers to express
concepts in fewer lines of code than possible in languages such
as C++ or Java.



Write a Python program to add a prefix text to all of the lines in a string.

In [108]:
import textwrap
sample_text ='''
    Python is a widely used high-level, general-purpose, interpreted,
    dynamic programming language. Its design philosophy emphasizes
    code readability, and its syntax allows programmers to express
    concepts in fewer lines of code than possible in languages such
    as C++ or Java.
    '''
text_without_Indentation = textwrap.dedent(sample_text)
wrapped = textwrap.fill(text_without_Indentation, width=50)
#wrapped += '\n\nSecond paragraph after a blank line.'
final_result = textwrap.indent(wrapped, '> ')
print()
print(final_result)
print()


>  Python is a widely used high-level, general-
> purpose, interpreted, dynamic programming
> language. Its design philosophy emphasizes code
> readability, and its syntax allows programmers to
> express concepts in fewer lines of code than
> possible in languages such as C++ or Java.



Write a Python program to set the indentation of the first line.

In [109]:
import textwrap
sample_text ='''
Python is a widely used high-level, general-purpose, interpreted, dynamic
programming language. Its design philosophy emphasizes code readability,
and its syntax allows programmers to express concepts in fewer lines of
code than possible in languages such as C++ or Java.
    '''

text1 =  textwrap.dedent(sample_text).strip()
print()
print(textwrap.fill(text1,
                    initial_indent='',
                    subsequent_indent=' ' * 4,
                    width=80,
                    ))
print()


Python is a widely used high-level, general-purpose, interpreted, dynamic
    programming language. Its design philosophy emphasizes code readability, and
    its syntax allows programmers to express concepts in fewer lines of code
    than possible in languages such as C++ or Java.



Write a Python program to print the following floating numbers upto 2 decimal places.

In [110]:
x=12.65565
y=2.65151
print('original x :',x)
print('formatted :'+"{:.2f}".format(x));
print('original y :',y)
print("{:.2f}".format(y))

original x : 12.65565
formatted :12.66
original y : 2.65151
2.65


Write a Python program to print the following floating numbers upto 2 decimal places with a sign

In [111]:
x=12.6421
y=-2.65454
print("{:+.2f}".format(x))
print("{:+.2f}".format(y))

+12.64
-2.65


Write a Python program to print the following floating numbers with no decimal places.

In [112]:
x=3.65454
y=2.999999
print("{:+.0f}".format(x))
print("{:+.0f}".format(y))

+4
+3


left pad

In [113]:
x=3212
print("{:*>7d}".format(x))

***3212


right pad

In [114]:
x=3212
print("{:*<7d}".format(x))

3212***


comma seperated

In [115]:
x=3000000000
print("{:,}".format(x))

3,000,000,000


Write a Python program to format a number with a percentage.

In [116]:
x=.65
print("{:.2%}".format(x))

65.00%


Write a Python program to display a number in left, right and center aligned of width 10.

In [117]:
x=22
print("{:10d}".format(x))
print("{:<10d}".format(x))
print("{:^10d}".format(x))

        22
22        
    22    


Write a Python program to count occurrences of a substring in a string.

In [118]:
str1="ashok fox lion tiger ashok"
str1.count('ashok')

2

Write a Python program to reverse a string

In [119]:
str1="ajsabdf"
rev=''.join(reversed(str1))
print(rev)

fdbasja


In [120]:
str1='ashok'
rev=str1[::-1]
print(rev)

kohsa


Write a Python program to reverse words in a string.

In [121]:
def funct(str1):
    for i in str1.split():
        return (''.join(reversed(str1)))
print(funct('skjdiw oijnf alnsf orijgrnl yufebf'))

fbefuy lnrgjiro fsnla fnjio widjks


Write a Python program to print the index of the character in a string.

In [127]:
str1="javascript"
for int1,char in enumerate(str1):
    print(char,int1)

j 0
a 1
v 2
a 3
s 4
c 5
r 6
i 7
p 8
t 9


 Write a Python program to check if a string contains all letters of the alphabet.

In [128]:
import string
alphabet=set(string.ascii_lowercase)
input1='kjsad sdfis dksd feo efoifne'
print(set(input1.lower())>=alphabet)
input2='The quick brown fox jumps over the lazy dog'
print(set(input2.lower())>=alphabet)

False
True


Write a Python program to swap comma and dot in a string.

In [129]:
str1="djlnsdf,sdkjfns,sdkjf,ksdj"
maketrans=str1.maketrans
print(str1.translate(maketrans(',','.')))
print(str1.replace(',','.'))


djlnsdf.sdkjfns.sdkjf.ksdj
djlnsdf.sdkjfns.sdkjf.ksdj


Write a Python program to count and display the vowels of a given text.

In [4]:
def funct(str1):
    vowels='aeiouAEIOU'
    count=0
    for i in str1:
        if i in vowels:
            count+=1
            #print(i[0:3],end=' ')
    #print(count)
    return count
funct('sjdf sefesdkjf akw seiuolksd')

7

In [131]:
def first_repeated_word(str1):
    temp = set()
    for word in str1.split():
        if word in temp:
            return word
        else:
            temp.add(word)
    return 'None'
print(first_repeated_word("ab ca bc ab"))
print(first_repeated_word("ab ca bc ab ca ab bc"))
print(first_repeated_word("ab ca bc ca ab bc"))
print(first_repeated_word("ab ca bc"))

ab
ab
ca
None


Write a Python program to capitalize first and last letters of each word of a given string.

In [132]:
def funct(str1):
    str1=result=str1.title()
    result=' '
    for i in str1.split():
        result+=i[:-1]+i[-1].upper()+' '
    return result[:-1]
print(funct('ksjf sdkf sfkjsf'))

 KsjF SdkF SfkjsF


Write a Python program to remove duplicate characters of a given string

In [133]:
from collections import OrderedDict
def remove_repeated(str1):
    return ''.join(OrderedDict.fromkeys(str1))
print(remove_repeated('ashok ashok dkjf kjfdng 123 123'))

ashok djfng123


Write a Python program to compute sum of digits of a given string.

In [134]:
import functools
def funct(str1):
    a=[]
    for i in str1:
        if i.isdigit():
            a.append(int(i))
    return(functools.reduce(lambda x,y : x+y,a))
print(funct('skjf6 dgd6f5 4gd1 5g'))

27


In [135]:
a=[32,65,12,5,6]
kjs=functools.reduce(lambda x,y:x+y,a)
print(kjs)

120


In [136]:
a=input('enter the string')
b=[]
for i in a:
    if i.isdigit():
        b.append(int(i))
print(functools.reduce(lambda x,y : x+y,b))


enter the stringkjnd87 f5435skhs78
47


In [138]:
import numpy as np
row=int(input('enter value for x'))
col=int(input('enter value for y'))
D=[[0 for col in range(col)] for row in range(row)]
for row in range(row):
    for col in range(col):
        D[row][col]=row*col
print(np.matrix(D))

enter value for x3
enter value for y5
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 2 4 0 0]]


In [140]:
row_count= int(input("Input number of rows: "))
col_count= int(input("Input number of columns: "))
multi_list = [[0 for col in range(col_count)] for row in range(row_count)]

for row in range(row_count):
    for col in range(col_count):
        multi_list[row][col]= row*col

print(np.matrix(multi_list))

Input number of rows: 3
Input number of columns: 5
[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [ ]:
2+3